dist: bionic
language: minimal
cache:
  ccache: true
  bundler: true
  directories:
  - $HOME/.rvm

addons:
  apt:
    packages:

env:
  global:
    - COMPOSERV=1.10.9

script:
  - sudo apt-get install ccache autoconf autopoint pigz libtool pkg-config tclsh bc bison zip unzip
  - gem install dpl
  - source vars.sh
  - ln -sf /bin/true `which pkgconfig`

  - |
    cd $WORK/deps/xz
    autoreconf -i
    ./configure --prefix=$WORK --disable-xz --disable-xzdec --disable-lzmadec --disable-lzmainfo --disable-scripts --disable-doc --disable-shared --enable-silent-rules >/dev/null
    make -j $CPUS
    make install

  - |
    cd $WORK/deps/zlib
    ./configure --const --static --64 --prefix=$WORK >/dev/null
    make -sj $CPUS
    make install

  - |
    cd $WORK/deps/libxml2
    autoreconf -i
    ./configure --prefix=$WORK --enable-silent-rules --disable-shared --with-pic --without-python >/dev/null
    make -j $CPUS
    make install

  - |
    cd $WORK/deps/sqlite
    ./configure --prefix=$WORK --disable-shared --enable-all --disable-gcov --with-pic --disable-tcl --disable-readline >/dev/null
    make -s
    make install

  - |
    cd $WORK/deps/re2c
    autoreconf -i
    ./configure --prefix=$WORK >/dev/null
    make -sj $CPUS
    make install

  - |
    cd $WORK/deps/openssl
    ./config no-shared no-engine no-dso --prefix=$WORK --openssldir=$WORK >/dev/null
    make -sj $CPUS
    make -s install &>/dev/null

  - |
    cd $WORK/deps/brotli
    ./bootstrap
    ./configure --prefix=$WORK --disable-shared --with-pic >/dev/null
    make -sj $CPUS
    make install

  - |
    cd $WORK/deps/curl
    autoreconf -i
    LIBS="-lbrotlicommon -lbrotlidec -lbrotlienc" ./configure --prefix=$WORK --enable-static --disable-shared --with-ssl=$WORK --with-nghttp2 --with-ngtcp2 --enable-alt-svc --with-libidn2 --with-brotli --disable-ldap >/dev/null
    make -sj $CPUS
    make install

  - |
    ls -lh $WORK/lib $WORK/include
    cd $WORK/deps/php-src
    ./buildconf --force
    ./configure --prefix=$WORK --with-openssl=$WORK LIBS="-l:libbrotlidec.a -l:libbrotlienc.a -l:libbrotlicommon.a -lpthread" SQLITE_CFLAGS="-I$WORK/include" SQLITE_LIBS="-L$WORK/lib -lsqlite3" CURL_CFLAGS="-I$WORK/include" CURL_LIBS="-L$WORK/lib -lcurl -l:libbrotlidec.a -l:libbrotlienc.a -l:libbrotlicommon.a -lpthread" OPENSSL_CFLAGS="-I$WORK/include" OPENSSL_LIBS="-L$WORK/lib -l:libssl.a -l:libcrypto.a -ldl -lpthread" --with-zlib --disable-cgi --enable-static || cat config.log
    make -sj $CPUS
    mkdir -p /tmp/dist
    [ -z $CI ] || make test &>/tmp/dist/php-test.log || true
    make install

  - |
    mkdir -p /tmp/$$/bin
    cd /tmp/$$
    cp $WORK/bin/php bin/
    strip bin/php
    ldd bin/php
    curl -sL https://getcomposer.org/download/$COMPOSERV/composer.phar > composer.phar
    bin/php composer.phar require guzzlehttp/guzzle
    zip -9r runtime.zip composer.* vendor
    pigz -K11 bin/php
    printf "@ php\n@=bin/php" | zipnote -w bin/php.zip
    mv bin/php.zip runtime.zip /tmp/dist/

deploy:
  provider: releases
  api_key:
    secure: SXFeInaUbW/sS0XaWZHaS1JyZd0sUnVygsnS7X0cxoABW9fVfud2oZY4X6wSjNBne2rqYKYqYmlKRIWA1M32yYxFt1tsPVoYXLkSsPLTBLOcMKMHtJ3SJAGDsTAnbSEQPHQ94Ol5dIvqsSXB/JYIENh2YNh/7EW5prExMRgz/VZhW5mmki/wYjBQntnA3OsAc9DORlK+4OMlf+To1Nf8IkBnO/2+yBARTWU4MU2rmLrEIEF4q/2g6spf7EPDzwQKv9pwUKb5rhtL7tLQgeskxIDlghC4BesqE0JKQfzDuNJ+Wym5hVCpVj11/Tc65zNr5Tpa7AYSz93vypwuiZhdm24o7J89xdw2Xv0xUGUezszoTSeM0tlhz04nGRxi9O/0rllOzXrAbVedyOL/wYvRRPdHVV9pFNHTzYAK8imYPORLzbnueKVacJ2FTdf0P4GcR8WUHxW5Kvk1XNMI6lKy0DVx1kf+0xjdSlG23ZFehH2QkMvfAncbYUtU3DxOHsobyXdZpA4Jpbudh1j6pkgRNpWRKfyZqhMudU1xaZfVHzoQIMW4A7Rvpj6PFc0WNKvYThuqlOHViNtt72wO8j+2IOTeZkPLSwu3zvzoS3Q7KWMewMtD/lHiY8GkteQ7W9Xhjd26AhpHUCVBYcheX/EBKN2EXw7c6eW0AQXxZVM37o8=
  file: "/tmp/dist/*"
  on:
    repo: jas88/lambda-for-php
  skip_cleanup: 'true'
