dist: bionic
language: c
cache: ccache

addons:
  apt:
    packages:

env:
  global:
    - COMPOSERV=1.10.9

script:
  - sudo apt-get install autoconf autopoint pigz libtool pkg-config tclsh bc bison zip unzip
  - |
    export WORK=$(pwd)
    export PKG_CONFIG_PATH=$WORK/lib/pkgconfig
    echo $PATH|fgrep -q $WORK/bin || export PATH=$WORK/bin:$PATH
    export CPUS=$(fgrep -c processor /proc/cpuinfo)
    export LDFLAGS=-L$WORK/lib
    export CPPFLAGS=-I$WORK/include

  - |
    cd $WORK/deps/xz
    autoreconf -i
    ./configure --prefix=$WORK --disable-xz --disable-xzdec --disable-lzmadec --disable-lzmainfo --disable-scripts --disable-doc --disable-shared --enable-silent-rules
    make -j $CPUS
    make install

  - |
    cd $WORK/deps/zlib
    ./configure --const --static --64 --prefix=$WORK
    make -sj $CPUS
    make install

  - |
    cd $WORK/deps/libxml2
    autoreconf -i
    ./configure --prefix=$WORK --enable-silent-rules --disable-shared --with-pic --without-python
    make -j $CPUS
    make install

  - |
    cd $WORK/deps/sqlite
    ./configure --prefix=$WORK --disable-shared --enable-all --disable-gcov --with-pic --disable-tcl --disable-readline
    make -s
    make install

  - |
    cd $WORK/deps/re2c
    autoreconf -i
    ./configure --prefix=$WORK
    make -sj $CPUS
    make install

  - |
    cd $WORK/deps/openssl
    ./config no-shared no-engine no-dso --prefix=$WORK --openssldir=$WORK
    make -j $CPUS
    make install

  - |
    cd $WORK/deps/brotli
    ./bootstrap
    ./configure --prefix=$WORK --disable-shared --with-pic
    make -sj $CPUS
    make install

  - |
    cd $WORK/deps/curl
    autoreconf -i
    LIBS=-lbrotlicommon ./configure --prefix=$WORK --enable-static --disable-shared --with-ssl=$WORK --with-nghttp2 --with-ngtcp2 --enable-alt-svc --with-libidn2 --with-brotli
    make -sj $CPUS
    make install

  - |
    cd $WORK/deps/php-src
    ./buildconf --force
    ./configure --prefix=$WORK --with-openssl=$WORK LIBS="-lpthread" SQLITE_CFLAGS="-I$WORK/include" SQLITE_LIBS="-L$WORK/lib -lsqlite3" OPENSSL_CFLAGS="-I$WORK/include" OPENSSL_LIBS="-L$WORK/lib -l:libssl.a -l:libcrypto.a -ldl -lpthread" --with-curl=$WORK --with-zlib --disable-cgi --enable-static
    make -sj $CPUS
    [ -z $CI ] || make test || true
    make install

  - |
    mkdir -p /tmp/$$/bin
    cd /tmp/$$
    cp $WORK/bin/php bin/
    strip bin/php
    pigz -K11 bin/php
    printf "@ php\n@=bin/php" | zipnote -w bin/php.zip
    curl -sL https://getcomposer.org/download/$COMPOSERV/composer.phar > composer.phar
    bin/php composer.phar require guzzlehttp/guzzle
    zip -9r runtime.zip composer.* vendor
